/** @type {import('stylelint').Config} */

const config = {
    extends: [
        "stylelint-config-standard-scss",
        "stylelint-config-recess-order",
        "stylelint-config-tailwindcss",
        "stylelint-config-sass-guidelines",
        "stylelint-config-prettier-scss",
    ],
    plugins: ["stylelint-order"],
    rules: {
        "color-hex-length": "long",
        "scss/operator-no-newline-before": null,
        "scss/operator-no-unspaced": null,
        "at-rule-no-unknown": null,
        "scss/at-rule-no-unknown": null,
        "scss/at-extend-no-missing-placeholder": null,
        "scss/dollar-variable-colon-space-after": null,
        "scss/dollar-variable-colon-space-before": null,
        "scss/double-slash-comment-empty-line-before": null,
        "selector-pseudo-class-no-unknown": [
            true,
            {
                ignorePseudoClasses: ["global", "has", "is"],
            },
        ],
        "import-notation": "string",
        "no-descending-specificity": null,
        "function-no-unknown": true,
        "no-unknown-animations": true,
        "no-unknown-custom-media": true,
        "unit-no-unknown": true,
        "at-rule-property-required-list": {
            "font-face": ["font-family", "src", "font-display"],
            supports: ["display"],
            property: ["property-name", "syntax", "initial-value", "inherits"],
            viewport: ["width", "height"],
            keyframes: ["from", "to"],
            container: ["container-type", "container-name"],
        },
        "color-hex-alpha": "never",
        "color-named": "never",
        "declaration-property-unit-disallowed-list": {
            "/^margin-block-start$/": ["px"],
            "/^margin-block-end$/": ["px"],
            "/^margin-inline-start$/": ["px"],
            "/^margin-inline-end$/": ["px"],
            "/^margin-block$/": ["px"],
            "/^margin-inline$/": ["px"],
            "/^padding-block-start$/": ["px"],
            "/^padding-block-end$/": ["px"],
            "/^padding-inline-start$/": ["px"],
            "/^padding-inline-end$/": ["px"],
            "/^padding-block$/": ["px"],
            "/^padding-inline$/": ["px"],
            "inline-size": ["px"],
            "block-size": ["px"],
            "min-inline-size": ["px"],
            "max-inline-size": ["px"],
            "min-block-size": ["px"],
            "max-block-size": ["px"],
            "/^border-block-start/": ["px"],
            "/^border-block-end/": ["px"],
            "/^border-inline-start/": ["px"],
            "/^border-inline-end/": ["px"],
            "/^border-block$/": ["px"],
            "/^border-inline$/": ["px"],
            "/^border-start/": ["px"],
            "/^border-end/": ["px"],
            "/^inset-block-start$/": ["px"],
            "/^inset-block-end$/": ["px"],
            "/^inset-inline-start$/": ["px"],
            "/^inset-inline-end$/": ["px"],
            "/^inset-block$/": ["px"],
            "/^inset-inline$/": ["px"],
            "/^inset$/": ["px"],
            "font-size": ["px"],
            "line-height": ["px"],
            "letter-spacing": ["px"],
            "word-spacing": ["px"],
            "text-indent": ["px"],
            "box-shadow": ["px"],
            "text-shadow": ["px"],
            "/^outline/": ["px"],
            "flex-basis": ["px"],
            "column-width": ["px"],
            "text-decoration-thickness": ["px"],
            "text-underline-offset": ["px"],
            "/^scroll-padding/": ["px"],
            perspective: ["px"],
            "/^gap$/": ["px"],
            "/^column-gap$/": ["px"],
            "/^row-gap$/": ["px"],
        },
        "declaration-property-unit-allowed-list": {
            "font-size": ["rem", "em", "%", "vw", "vmin", "vmax"],
            "line-height": ["%", "em", "rem"],
            "letter-spacing": ["em", "rem"],
            "word-spacing": ["em", "rem"],
            "text-indent": ["em", "rem", "%"],
            "/^margin-block-start$/": ["rem", "em", "%"],
            "/^margin-block-end$/": ["rem", "em", "%"],
            "/^margin-inline-start$/": ["rem", "em", "%"],
            "/^margin-inline-end$/": ["rem", "em", "%"],
            "/^margin-block$/": ["rem", "em", "%"],
            "/^margin-inline$/": ["rem", "em", "%"],
            "/^padding-block-start$/": ["rem", "em", "%"],
            "/^padding-block-end$/": ["rem", "em", "%"],
            "/^padding-inline-start$/": ["rem", "em", "%"],
            "/^padding-inline-end$/": ["rem", "em", "%"],
            "/^padding-block$/": ["rem", "em", "%"],
            "/^padding-inline$/": ["rem", "em", "%"],
            "inline-size": ["%", "rem", "em", "vw", "dvw", "ch", "vmin", "vmax"],
            "block-size": ["vh", "dvh", "lvh", "svh", "rem", "em", "%", "vw", "dvw", "vmin", "vmax"],
            "min-inline-size": ["rem", "em", "%", "vw", "dvw", "ch"],
            "max-inline-size": ["rem", "em", "%", "vw", "dvw", "ch", "vmin", "vmax"],
            "min-block-size": ["vh", "dvh", "lvh", "svh", "rem", "em", "%"],
            "max-block-size": ["vh", "dvh", "lvh", "svh", "rem", "em", "%", "vw", "dvw"],
            "/^border-block-start/": ["em", "rem"],
            "/^border-block-end/": ["em", "rem"],
            "/^border-inline-start/": ["em", "rem"],
            "/^border-inline-end/": ["em", "rem"],
            "/^border-block$/": ["em", "rem"],
            "/^border-inline$/": ["em", "rem"],
            "/^border-start/": ["em", "rem"],
            "/^border-end/": ["em", "rem"],
            "/^border-start-start-radius$/": ["em", "rem", "%"],
            "/^border-start-end-radius$/": ["em", "rem", "%"],
            "/^border-end-end-radius$/": ["em", "rem", "%"],
            "/^border-end-start-radius$/": ["em", "rem", "%"],
            "/^inset-block-start$/": ["%", "rem", "em", "vh", "vw"],
            "/^inset-block-end$/": ["%", "rem", "em", "vh", "vw"],
            "/^inset-inline-start$/": ["%", "rem", "em", "vh", "vw"],
            "/^inset-inline-end$/": ["%", "rem", "em", "vh", "vw"],
            "/^inset-block$/": ["%", "rem", "em", "vh", "vw"],
            "/^inset-inline$/": ["%", "rem", "em", "vh", "vw"],
            "/^inset$/": ["%", "rem", "em", "vh", "vw"],
            "box-shadow": ["em", "rem"],
            "text-shadow": ["em", "rem"],
            filter: ["%"],
            "flex-basis": ["%", "rem", "em", "vw", "dvw"],
            "column-width": ["em", "rem", "ch"],
            "text-decoration-thickness": ["em", "rem", "%"],
            "text-underline-offset": ["em", "rem"],
            "/^scroll-padding-block-start$/": ["rem", "em", "%"],
            "/^scroll-padding-block-end$/": ["rem", "em", "%"],
            "/^scroll-padding-inline-start$/": ["rem", "em", "%"],
            "/^scroll-padding-inline-end$/": ["rem", "em", "%"],
            "/^scroll-padding-block$/": ["rem", "em", "%"],
            "/^scroll-padding-inline$/": ["rem", "em", "%"],
            "/^scroll-padding$/": ["rem", "em", "%"],
            perspective: ["rem", "em"],
            "/^gap$/": ["rem", "em", "%"],
            "/^column-gap$/": ["rem", "em", "%"],
            "/^row-gap$/": ["rem", "em", "%"],
            "/^(transition|animation)-delay$/": ["ms"],
            "/^(transition|animation)-duration$/": ["ms"],
            "/^outline-offset$/": ["em", "rem"],
            "/^outline-width$/": ["em", "rem"],
        },
        "function-url-scheme-disallowed-list": ["http", "https", "/^http/"],
        "function-url-scheme-allowed-list": ["data", "/^file/"],
        "media-feature-name-disallowed-list": ["min-width", "max-width", "min-height", "max-height"],
        "media-feature-name-unit-allowed-list": {
            width: ["rem", "em", "ch"],
            height: ["rem", "em", "ch"],
            "aspect-ratio": [],
            color: [],
            "color-index": [],
            monochrome: [],
            resolution: ["dpi", "dpcm"],
        },
        "media-feature-name-value-allowed-list": {
            orientation: ["portrait", "landscape"],
            scan: ["interlace", "progressive"],
            grid: ["0", "1"],
            update: ["none", "slow", "fast"],
            "overflow-block": ["none", "scroll", "optional-paged", "paged"],
            "overflow-inline": ["none", "scroll"],
            "prefers-color-scheme": ["light", "dark", "no-preference"],
            "prefers-reduced-motion": ["reduce", "no-preference"],
            "prefers-reduced-transparency": ["reduce", "no-preference"],
            "prefers-reduced-data": ["reduce", "no-preference"],
            "prefers-contrast": ["more", "less", "custom", "no-preference"],
            "prefers-forced-colors": ["active", "none"],
            pointer: ["none", "coarse", "fine"],
            hover: ["none", "hover"],
            "any-pointer": ["none", "coarse", "fine"],
            "any-hover": ["none", "hover"],
            "color-gamut": ["srgb", "p3", "rec2020"],
            "display-mode": ["fullscreen", "standalone", "minimal-ui", "browser"],
            "forced-colors": ["none", "active"],
            "inverted-colors": ["none", "inverted"],
            "light-level": ["dim", "normal", "washed"],
            "video-dynamic-range": ["standard", "high"],
            "video-color-gamut": ["srgb", "p3", "rec2020"],
        },
        "property-disallowed-list": [
            "width",
            "height",
            "min-width",
            "max-width",
            "min-height",
            "max-height",
            "margin-top",
            "margin-bottom",
            "margin-left",
            "margin-right",
            "padding-top",
            "padding-bottom",
            "padding-left",
            "padding-right",
            "border-top",
            "border-bottom",
            "border-left",
            "border-right",
            "border-top-width",
            "border-bottom-width",
            "border-left-width",
            "border-right-width",
            "border-top-style",
            "border-bottom-style",
            "border-left-style",
            "border-right-style",
            "border-top-color",
            "border-bottom-color",
            "border-left-color",
            "border-right-color",
            "border-top-left-radius",
            "border-top-right-radius",
            "border-bottom-right-radius",
            "border-bottom-left-radius",
            "top",
            "bottom",
            "left",
            "right",
            "clear",
            "float",
        ],
        "selector-no-qualifying-type": true,
        "unit-disallowed-list": ["px"],
        "max-nesting-depth": 5,
        "font-weight-notation": "numeric",
    },
    ignoreFiles: ["node_modules/**", ".next/**", "dist/**", "build/**", "coverage/**"],
};

export default config;
