import { getCollectedCSS } from "../styles/style-registry";

function extractAcClassesFromHTML(html: string): Set<string> {
    const classes = new Set<string>();

    // outerHTML will typically use double quotes, but handle both for safety.
    const classAttrRegex = /class\s*=\s*(?:"([^"]*)"|'([^']*)')/g;
    let match: RegExpExecArray | null;

    while ((match = classAttrRegex.exec(html)) !== null) {
        const classValue = (match[1] ?? match[2] ?? "").trim();
        if (!classValue) {
            continue;
        }

        for (const cls of classValue.split(/\s+/)) {
            if (cls.startsWith("ac-")) {
                classes.add(cls);
            }
        }
    }

    return classes;
}

function filterCSSByUsedClasses(css: string, usedClasses: Set<string>): string {
    if (!css.trim() || usedClasses.size === 0) {
        return "";
    }

    // Match rules generated by registerStyle():
    // .ac-xxxxxxxx { ... }
    const ruleRegex = /\.([A-Za-z0-9_-]+)\s*\{[^}]*\}/g;
    const keptRules: string[] = [];
    let match: RegExpExecArray | null;

    while ((match = ruleRegex.exec(css)) !== null) {
        const className = match[1];
        if (usedClasses.has(className)) {
            keptRules.push(match[0]);
        }
    }

    return keptRules.join("\n");
}

/**
 * Returns ONLY the CSS needed for the current exported HTML.
 * This prevents exporting historical/unused classes accumulated while tweaking controls.
 */
export function getWidgetCSS(exportedHTML: string): string {
    const css = getCollectedCSS();

    if (!css.trim()) {
        // eslint-disable-next-line no-console
        console.warn("No widget CSS found to export");
        return "";
    }

    const usedClasses = extractAcClassesFromHTML(exportedHTML);
    const filtered = filterCSSByUsedClasses(css, usedClasses);

    if (!filtered.trim()) {
        // eslint-disable-next-line no-console
        console.warn("Widget CSS was collected, but no matching classes were found in exported HTML");
        return "";
    }

    return filtered;
}
